#=======================================================================
# Makefrag for rv64si tests
#-----------------------------------------------------------------------

rv64si_test_target = \
	csr \
	dirty \
	icache-alias \
	ma_fetch \
	scall \
	wfi \
	sbreak \

rv64si_test_src = $(addsuffix .S, $(rv64si_sc_tests))
