#=======================================================================
# Makefrag for rv64uf tests
#-----------------------------------------------------------------------

rv64uf_test_target = \
	fadd fdiv fclass fcmp fcvt fcvt_w fmadd fmin \
	ldst move recoding \

rv64uf_test_src = $(addsuffix .S, $(rv64uf_sc_tests))
